// packages/cli/templates/vue/src/App.vue
<script setup>
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useShellui } from './composables/useShellui'

const { t } = useI18n()
const { theme, language } = useShellui()

const themeText = computed(() => {
  const current = theme.value
  if (!current) return t('fallbackTheme')
  const name = current.displayName || current.name || 'shellui'
  return `${name} · ${current.mode}`
})
</script>

<template>
  <main class="shellui-home">
    <p class="eyebrow">Shellui</p>
    <h1>{{ t('title') }}</h1>
    <p class="blurb">{{ t('blurb') }}</p>

    <dl class="meta">
      <div>
        <dt>{{ t('themeLabel') }}</dt>
        <dd>{{ themeText }}</dd>
      </div>
      <div>
        <dt>{{ t('languageLabel') }}</dt>
        <dd>{{ language || t('fallbackLanguage') }}</dd>
      </div>
    </dl>

    <p class="hint">{{ t('hint') }}</p>
  </main>
</template>

// packages/cli/templates/react/src/App.jsx
import { useTranslation } from 'react-i18next'
import { useShellui } from './useShellui'
import './App.css'

function themeLabel(theme, t) {
  if (!theme) return t('fallbackTheme')
  const name = theme.displayName || theme.name || 'shellui'
  return `${name} · ${theme.mode}`
}

function App() {
  const { t } = useTranslation()
  const { theme, language } = useShellui()

  return (
    <main className="shellui-home">
      <p className="eyebrow">Shellui</p>
      <h1>{t('title')}</h1>
      <p className="blurb">{t('blurb')}</p>

      <dl className="meta">
        <div>
          <dt>{t('themeLabel')}</dt>
          <dd>{themeLabel(theme, t)}</dd>
        </div>
        <div>
          <dt>{t('languageLabel')}</dt>
          <dd>{language || t('fallbackLanguage')}</dd>
        </div>
      </dl>

      <p className="hint">{t('hint')}</p>
    </main>
  )
}

export default App
